// Code generated by goctl. DO NOT EDIT!
// Source: test.proto

package checker

import (
	"context"

	"rapid-development-microservices/rpc/test/test"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckReq  = test.CheckReq
	CheckResp = test.CheckResp

	Checker interface {
		Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error)
		Check1(ctx context.Context, in *CheckReq1, opts ...grpc.CallOption) (*CheckResp1, error)
	}

	defaultChecker struct {
		cli zrpc.Client
	}
)

func NewChecker(cli zrpc.Client) Checker {
	return &defaultChecker{
		cli: cli,
	}
}

func (m *defaultChecker) Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error) {
	client := test.NewCheckerClient(m.cli.Conn())
	return client.Check(ctx, in, opts...)
}

func (m *defaultChecker) Check1(ctx context.Context, in *CheckReq1, opts ...grpc.CallOption) (*CheckResp1, error) {
	client := test.NewCheckerClient(m.cli.Conn())
	return client.Check1(ctx, in, opts...)
}
